import {
  Loader2,
  Upload,
  File,
  Trash,
  Settings,
  Puzzle,
  Shield,
  Plus,
  Slack,
  Calendar,
  Database,
  CreditCard,
  Github,
  Headphones,
} from "lucide-react"

export const Icons = {
  spinner: Loader2,
  upload: Upload,
  file: File,
  trash: Trash,
  settings: Settings,
  puzzle: Puzzle,
  shield: Shield,
  plus: Plus,
  slack: Slack,
  calendar: Calendar,
  database: Database,
  creditCard: CreditCard,
  github: Github,
  headset: Headphones,
} as const